name: brod
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master
env:
  OTP_VERSION: "24.1"
  REBAR_VERSION: "3.17.0"

jobs:
  lint:
    runs-on: ubuntu-20.04
    name: Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: OTP
        uses: erlef/setup-beam@v1
        with:
          version-type: strict
          otp-version: ${{ env.OTP_VERSION }}
          rebar3-version: ${{ env.REBAR_VERSION }}
      - name: Cache Build
        id: cache-lint-hex
        uses: actions/cache@v3
        with:
          path: _build
          key: ${{ runner.os }}-${{ env.OTP_VERSION }}-rebar-${{ hashFiles('**/rebar.lock') }}
          restore-keys: ${{ runner.os }}-rebar-
      - name: Cache Dialyzer PLTs
        uses: actions/cache@v3
        with:
          path: ~/.cache/rebar3/rebar3_*_plt
          key: ${{ runner.os }}-dialyzer-${{ hashFiles('**/rebar.lock') }}
          restore-keys: ${{ runner.os }}-dialyzer-
      - name: Lint, Dialyzer & Xref
        run: rebar3 do compile,lint,dialyzer,xref
  build:
    runs-on: ubuntu-20.04
    name: OTP ${{matrix.otp}} / Kafka ${{matrix.kafka}}
    strategy:
      fail-fast: false
      matrix:
        otp: ["24.1", "23.3.4.7", "22.3.4.21"]
        kafka: ["2.4", "1.1", "0.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Build
        uses: actions/cache@v3
        with:
          path: _build
          key: ${{ runner.os }}-${{ matrix.otp }}-rebar-${{ hashFiles('**/rebar.lock') }}
          restore-keys: ${{ runner.os }}-${{ matrix.otp }}-rebar-
      - name: Install Erlang
        uses: erlef/setup-beam@v1
        with:
          version-type: strict
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{ env.REBAR_VERSION }}
      - name: Compile
        run: rebar3 do compile
      - name: Make brod_cli script
        run: rebar3 as brod_cli escriptize
      - name: Run tests
        run: |
          export KAFKA_VERSION=${{ matrix.kafka }}
          echo "Running Kafka ${KAFKA_VERSION}"
          scripts/setup-test-env.sh && rebar3 do ct,eunit
